# Generated by Django 4.2.3 on 2023-10-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breath_collection",
            name="collection_time",
            field=models.TimeField(verbose_name="collection time"),
        ),
    ]
