# Generated by Django 4.2.3 on 2023-10-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0003_remove_breath_collection_casper_barcode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breath_collection",
            name="volume_collected",
            field=models.CharField(blank=True, default=0, max_length=7, null=True),
        ),
    ]
