# Generated by Django 4.2.3 on 2023-10-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0004_alter_breath_collection_volume_collected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ct_scan",
            name="cat_5_comments",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="ct_scan",
            name="copd_emphysema_extent",
            field=models.TextField(
                choices=[
                    ("None", "None"),
                    ("Trace", "Trace"),
                    ("Mild", "Mild"),
                    ("Moderate", "Moderate"),
                    ("Severe", "Severe"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ct_scan_nodule_1",
            name="nodule_interval_change",
            field=models.TextField(
                choices=[
                    ("New", "New"),
                    ("Stable", "Stable"),
                    ("Increased", "Increased"),
                    ("Decreased", "Decreased"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ct_scan_nodule_1",
            name="nodule_interval_change_cad",
            field=models.TextField(
                choices=[
                    ("New", "New"),
                    ("Stable", "Stable"),
                    ("Increased", "Increased"),
                    ("Decreased", "Decreased"),
                ],
                default=None,
                max_length=20,
            ),
        ),
    ]
