# Generated by Django 4.2.3 on 2023-10-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0005_alter_ct_scan_cat_5_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ct_scan_nodule_1",
            name="nodule_description",
            field=models.TextField(
                choices=[
                    ("Smooth", "Smooth"),
                    ("lobulated", "Lobulated"),
                    ("spiculated", "Spiculated"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ct_scan_nodule_1",
            name="nodule_description_cad",
            field=models.TextField(
                choices=[
                    ("Smooth", "Smooth"),
                    ("lobulated", "Lobulated"),
                    ("spiculated", "Spiculated"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ct_scan_nodule_1",
            name="nodule_location",
            field=models.TextField(
                choices=[
                    ("Parenchymal", "Parenchymal"),
                    ("Airway", "Airway"),
                    ("Juxtapleural", "Juxtapleural"),
                    ("Fissural", "Fissural"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ct_scan_nodule_1",
            name="nodule_location_cad",
            field=models.TextField(
                choices=[
                    ("Parenchymal", "Parenchymal"),
                    ("Airway", "Airway"),
                    ("Juxtapleural", "Juxtapleural"),
                    ("Fissural", "Fissural"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ct_scan_nodule_1",
            name="nodule_type",
            field=models.TextField(
                choices=[
                    ("Solid", "Solid"),
                    ("Non-Solid", "Non-Solid"),
                    ("Part Solid", "Part Solid"),
                    ("Calcified", "Calcified"),
                    ("PFN", "PFN"),
                    ("Cystic", "Cystic"),
                    ("N/A", "N/A"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ct_scan_nodule_1",
            name="nodule_type_cad",
            field=models.TextField(
                choices=[
                    ("Solid", "Solid"),
                    ("Non-Solid", "Non-Solid"),
                    ("Part Solid", "Part Solid"),
                    ("Calcified", "Calcified"),
                    ("PFN", "PFN"),
                    ("Cystic", "Cystic"),
                    ("N/A", "N/A"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ct_scan_nodule_2",
            name="nodule_type",
            field=models.TextField(
                choices=[
                    ("Solid", "Solid"),
                    ("Non-Solid", "Non-Solid"),
                    ("Part Solid", "Part Solid"),
                    ("Calcified", "Calcified"),
                    ("PFN", "PFN"),
                    ("Cystic", "Cystic"),
                    ("N/A", "N/A"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ct_scan_nodule_2",
            name="nodule_type_cad",
            field=models.TextField(
                choices=[
                    ("Solid", "Solid"),
                    ("Non-Solid", "Non-Solid"),
                    ("Part Solid", "Part Solid"),
                    ("Calcified", "Calcified"),
                    ("PFN", "PFN"),
                    ("Cystic", "Cystic"),
                    ("N/A", "N/A"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ct_scan_nodule_3",
            name="nodule_type",
            field=models.TextField(
                choices=[
                    ("Solid", "Solid"),
                    ("Non-Solid", "Non-Solid"),
                    ("Part Solid", "Part Solid"),
                    ("Calcified", "Calcified"),
                    ("PFN", "PFN"),
                    ("Cystic", "Cystic"),
                    ("N/A", "N/A"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ct_scan_nodule_3",
            name="nodule_type_cad",
            field=models.TextField(
                choices=[
                    ("Solid", "Solid"),
                    ("Non-Solid", "Non-Solid"),
                    ("Part Solid", "Part Solid"),
                    ("Calcified", "Calcified"),
                    ("PFN", "PFN"),
                    ("Cystic", "Cystic"),
                    ("N/A", "N/A"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ct_scan_nodule_4",
            name="nodule_type",
            field=models.TextField(
                choices=[
                    ("Solid", "Solid"),
                    ("Non-Solid", "Non-Solid"),
                    ("Part Solid", "Part Solid"),
                    ("Calcified", "Calcified"),
                    ("PFN", "PFN"),
                    ("Cystic", "Cystic"),
                    ("N/A", "N/A"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ct_scan_nodule_4",
            name="nodule_type_cad",
            field=models.TextField(
                choices=[
                    ("Solid", "Solid"),
                    ("Non-Solid", "Non-Solid"),
                    ("Part Solid", "Part Solid"),
                    ("Calcified", "Calcified"),
                    ("PFN", "PFN"),
                    ("Cystic", "Cystic"),
                    ("N/A", "N/A"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ct_scan_nodule_5",
            name="nodule_type",
            field=models.TextField(
                choices=[
                    ("Solid", "Solid"),
                    ("Non-Solid", "Non-Solid"),
                    ("Part Solid", "Part Solid"),
                    ("Calcified", "Calcified"),
                    ("PFN", "PFN"),
                    ("Cystic", "Cystic"),
                    ("N/A", "N/A"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ct_scan_nodule_5",
            name="nodule_type_cad",
            field=models.TextField(
                choices=[
                    ("Solid", "Solid"),
                    ("Non-Solid", "Non-Solid"),
                    ("Part Solid", "Part Solid"),
                    ("Calcified", "Calcified"),
                    ("PFN", "PFN"),
                    ("Cystic", "Cystic"),
                    ("N/A", "N/A"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="casper_tennax",
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="reciva_tennax",
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="room_air_tennax",
            field=models.IntegerField(max_length=6),
        ),
    ]
