# Generated by Django 4.2.3 on 2023-10-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0006_alter_ct_scan_nodule_1_nodule_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breath_collection",
            name="tennax_number",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lab_processing",
            name="casper_tennax",
            field=models.PositiveIntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="biological_relatives_cancer",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
