# Generated by Django 4.2.3 on 2023-10-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0007_alter_breath_collection_tennax_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="birthplace",
            field=models.TextField(default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="children",
            field=models.TextField(default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="highest_education_lvl_other",
            field=models.TextField(default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="num_brothers",
            field=models.TextField(default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="num_half_brothers",
            field=models.TextField(default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="num_half_sisters",
            field=models.TextField(default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="num_sisters",
            field=models.TextField(default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="year_moved_to_canada",
            field=models.TextField(default=False, max_length=4, null=True),
        ),
    ]
