# Generated by Django 4.2.3 on 2023-11-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0008_alter_mandatory_questionaire_birthplace_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="biological_relatives_cancer",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="children",
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="num_brothers",
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="num_half_brothers",
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="num_half_sisters",
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="num_sisters",
            field=models.TextField(max_length=20, null=True),
        ),
    ]
