# Generated by Django 4.2.3 on 2023-11-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "DataEntry",
            "0009_alter_mandatory_questionaire_biological_relatives_cancer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatory_questionaire",
            name="year_moved_to_canada",
            field=models.TextField(default="N/A", max_length=4, null=True),
        ),
    ]
