# Generated by Django 4.2.3 on 2023-11-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0010_alter_mandatory_questionaire_year_moved_to_canada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exposure2",
            name="sulfur",
            field=models.TextField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("Dont Know", "Dont Know"),
                    ("N/A", "N/A"),
                ],
                default="No",
                max_length=10,
                null=True,
            ),
        ),
    ]
