# Generated by Django 4.2.3 on 2023-11-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0011_alter_exposure2_sulfur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_1",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_2",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_3",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_4",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_5",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_6",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_7",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_8",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_9",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_9_a",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_9_b",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_9_c",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inclusion",
            name="inclusion_criteria_9_d",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
