# Generated by Django 4.2.3 on 2023-11-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0012_alter_inclusion_inclusion_criteria_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breath_collection",
            name="brush_teeth_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="brush teeth time"
            ),
        ),
    ]
