# Generated by Django 4.2.3 on 2023-11-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0013_alter_breath_collection_brush_teeth_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breath_collection",
            name="collection_start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="collection start time"
            ),
        ),
        migrations.AlterField(
            model_name="breath_collection",
            name="collection_stop_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="collection stop time"
            ),
        ),
        migrations.AlterField(
            model_name="breath_collection",
            name="last_drink_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="last drink time"
            ),
        ),
        migrations.AlterField(
            model_name="breath_collection",
            name="last_meal_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="last meal time"
            ),
        ),
        migrations.AlterField(
            model_name="breath_collection",
            name="room_air_collection_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="room air collection time"
            ),
        ),
    ]
