# Generated by Django 4.2.3 on 2023-11-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0015_alter_breath_collection_casper_collection_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breath_collection",
            name="collection_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="mandatory_questionaire_de",
            name="second_hand_exposure_time",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Less than 2 hours", "Less than 2 hours"),
                    ("2-4 hours", "2-4 hours"),
                    ("4-6 hours", "4-6 hours"),
                    ("6 plus hours", "6 plus hours"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
