# Generated by Django 4.2.3 on 2023-11-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0017_alter_exposure2_coal_gasification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exposure2",
            name="coal_gasification",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("Dont Know", "Dont Know"),
                    ("N/A", "N/A"),
                ],
                default="No",
                max_length=20,
                null=True,
            ),
        ),
    ]
