# Generated by Django 4.2.3 on 2023-11-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0018_alter_exposure2_coal_gasification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exposure2",
            name="cooking_appliances",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Open Window", "Open Window"),
                    ("Chimney", "Chimney"),
                    ("Exhaust Fan", "Exhaust Fan"),
                    ("Partially open to outside", "Partially open to outside"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
