# Generated by Django 4.2.3 on 2023-11-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataEntry", "0019_alter_exposure2_cooking_appliances"),
    ]

    operations = [
        migrations.AddField(
            model_name="inclusion",
            name="participant_status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("IPN", "IPN"),
                    ("Cancer", "Cancer"),
                    ("Control", "Control"),
                    ("Stable Nodule", "Stable Nodule"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
